[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/snapview/tungstenite-rs"
documentation = "https://docs.rs/tungstenite/0.5.4"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.6.0"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "0.9.2"
byteorder = "1.2.3"
bytes = "0.4.8"
httparse = "1.3.1"
input_buffer = "0.2.0"
log = "0.4.2"
rand = "0.5.2"
sha-1 = "0.7"
url = "1.7.0"
utf-8 = "0.7.2"
faster = {git = "https://github.com/AdamNiederer/faster.git"}

[dependencies.native-tls]
optional = true
version = "0.2"

[dev-dependencies]
env_logger = "0.5.3"
criterion = "0.2"

[[bench]]
name = "masking"
harness = false